//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrakeForce
    {
        public int BrakeForceID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> FrontLeftBrake { get; set; }
        public Nullable<decimal> RearLeftBrake { get; set; }
        public Nullable<decimal> HandBrakeLeft { get; set; }
        public Nullable<decimal> HandBrakeRight { get; set; }
        public Nullable<decimal> FrontRightBrake { get; set; }
        public Nullable<decimal> RearRightBrake { get; set; }
    
        public virtual VehicleInfo VehicleInfo { get; set; }
    }
}
