//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calibration
    {
        public int CalibrationID { get; set; }
        public string ParaType { get; set; }
        public Nullable<decimal> ParaA { get; set; }
        public Nullable<decimal> ParaB { get; set; }
    }
}
