//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasEmission_Petrol
    {
        public int GasEmissionID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> HC { get; set; }
        public Nullable<decimal> CO { get; set; }
        public Nullable<decimal> CO2 { get; set; }
        public Nullable<decimal> O2 { get; set; }
        public Nullable<decimal> NO { get; set; }
        public Nullable<decimal> OilTemp { get; set; }
        public Nullable<int> RPM { get; set; }
        public Nullable<decimal> Lambda { get; set; }
    
        public virtual VehicleInfo VehicleInfo { get; set; }
    }
}
