//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasEmission_Diesel
    {
        public int GasEmissionID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> MinSpeed1 { get; set; }
        public Nullable<decimal> MaxSpeed1 { get; set; }
        public Nullable<decimal> HSU1 { get; set; }
        public Nullable<decimal> MinSpeed2 { get; set; }
        public Nullable<decimal> MaxSpeed2 { get; set; }
        public Nullable<decimal> HSU2 { get; set; }
        public Nullable<decimal> MinSpeed3 { get; set; }
        public Nullable<decimal> MaxSpeed3 { get; set; }
        public Nullable<decimal> HSU3 { get; set; }
    
        public virtual VehicleInfo VehicleInfo { get; set; }
    }
}
