//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Headlight
    {
        public int HeadlightsID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> LeftHBIntensity { get; set; }
        public Nullable<decimal> LeftHBVerticalDeviation { get; set; }
        public Nullable<decimal> LeftHBHorizontalDeviation { get; set; }
        public Nullable<decimal> RightHBIntensity { get; set; }
        public Nullable<decimal> RightHBVerticalDeviation { get; set; }
        public Nullable<decimal> RightHBHorizontalDeviation { get; set; }
        public Nullable<decimal> LeftLBIntensity { get; set; }
        public Nullable<decimal> LeftLBVerticalDeviation { get; set; }
        public Nullable<decimal> LeftLBHorizontalDeviation { get; set; }
        public Nullable<decimal> RightLBIntensity { get; set; }
        public Nullable<decimal> RightLBVerticalDeviation { get; set; }
        public Nullable<decimal> RightLBHorizontalDeviation { get; set; }
    
        public virtual VehicleInfo VehicleInfo { get; set; }
    }
}
