//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SideSlip
    {
        public int SideSlipID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> SideSlip1 { get; set; }
    
        public virtual VehicleInfo VehicleInfo { get; set; }
    }
}
