//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInfo()
        {
            this.BrakeForces = new HashSet<BrakeForce>();
            this.GasEmission_Diesel = new HashSet<GasEmission_Diesel>();
            this.GasEmission_Petrol = new HashSet<GasEmission_Petrol>();
            this.Headlights = new HashSet<Headlight>();
            this.Noises = new HashSet<Noise>();
            this.SideSlips = new HashSet<SideSlip>();
            this.Speeds = new HashSet<Speed>();
            this.SteerAngles = new HashSet<SteerAngle>();
            this.Weights = new HashSet<Weight>();
        }
    
        public string FrameNumber { get; set; }
        public string VehicleType { get; set; }
        public string Inspector { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public int VehicleID { get; set; }
        public string Fuel { get; set; }
        public string Color { get; set; }
        public string EngineType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrakeForce> BrakeForces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GasEmission_Diesel> GasEmission_Diesel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GasEmission_Petrol> GasEmission_Petrol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Headlight> Headlights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noise> Noises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SideSlip> SideSlips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Speed> Speeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SteerAngle> SteerAngles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Weight> Weights { get; set; }
    }
}
