//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenAIS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleStandard
    {
        public string VehicleType { get; set; }
        public Nullable<decimal> MinSpeed { get; set; }
        public Nullable<decimal> MaxSpeed { get; set; }
        public Nullable<decimal> MinFrontBrake { get; set; }
        public Nullable<decimal> MinRearBrake { get; set; }
        public Nullable<decimal> MinHandBrake { get; set; }
        public Nullable<decimal> MaxDiffFrontBrake { get; set; }
        public Nullable<decimal> MaxDiffRearBrake { get; set; }
        public Nullable<decimal> MaxDiffHandBrake { get; set; }
        public Nullable<decimal> MaxNoise { get; set; }
        public Nullable<decimal> MinWhistle { get; set; }
        public Nullable<decimal> MaxWhistle { get; set; }
        public Nullable<decimal> MinSideSlip { get; set; }
        public Nullable<decimal> MaxSideSlip { get; set; }
        public Nullable<decimal> MaxHC { get; set; }
        public Nullable<decimal> MaxCO { get; set; }
        public Nullable<decimal> MaxCO2 { get; set; }
        public Nullable<decimal> MaxO2 { get; set; }
        public Nullable<decimal> MaxNO { get; set; }
        public Nullable<decimal> MaxHSU { get; set; }
        public Nullable<decimal> MaxDiesel { get; set; }
        public Nullable<decimal> MinHLIntensity { get; set; }
        public Nullable<decimal> MinDiffHoriLeftHB { get; set; }
        public Nullable<decimal> MaxDiffHoriLeftHB { get; set; }
        public Nullable<decimal> MinDiffHoriHB { get; set; }
        public Nullable<decimal> MaxDiffHoriHB { get; set; }
        public Nullable<decimal> MinDiffVertiHB { get; set; }
        public Nullable<decimal> MaxDiffVertiHB { get; set; }
        public Nullable<decimal> MinDiffHoriLB { get; set; }
        public Nullable<decimal> MaxDiffHoriLB { get; set; }
        public Nullable<decimal> MinDiffVertiLB { get; set; }
        public Nullable<decimal> MaxDiffVertiLB { get; set; }
        public Nullable<decimal> MinLBIntensity { get; set; }
        public Nullable<decimal> MinLightHeight { get; set; }
        public Nullable<decimal> MinLeftSteer { get; set; }
        public Nullable<decimal> MinRightSteer { get; set; }
        public Nullable<decimal> MaxLeftSteer { get; set; }
        public Nullable<decimal> MaxRightSteer { get; set; }
        public Nullable<decimal> MinFLIntensity { get; set; }
        public Nullable<decimal> MaxFLIntensity { get; set; }
        public Nullable<decimal> MinDiffHoriFL { get; set; }
        public Nullable<decimal> MaxDiffHoriFL { get; set; }
        public Nullable<decimal> MinDiffVertiFL { get; set; }
        public Nullable<decimal> MaxDiffVertiFL { get; set; }
        public Nullable<decimal> MinFLHeight { get; set; }
        public Nullable<decimal> MaxFLHeight { get; set; }
        public Nullable<decimal> MaxLightHeight { get; set; }
        public string SampleVin { get; set; }
        public string SampleEngine { get; set; }
        public Nullable<decimal> MinLamda { get; set; }
        public Nullable<decimal> MaxLamda { get; set; }
    }
}
